### ISSUE TITLE
需要接收到串口数据才会发送命令

### ISSUE THREAD

**Issue by lmyun** [armink/FreeModbus_Slave-Master-RTT-STM32#20]
第一次执行eMBMasterReqReadInputRegister(1,3,2,RT_WAITING_FOREVER);时不发送命令（远程串口调试助手收不到信息），只有当远程串口调试助手发送东西给FreeModbus-STM32后工作就正常了，这是怎么回事？

**Comment by armink** [comment]
- 把问题描述在详细点，有助于进一步帮你分析问题，还有你的说远程串口助手是什么？
- 再者，需要注意的是，单片机作为主机，是不允许从机主动跟主机通信的；
- 是否有直接使用 GitHub 上的源码编译、下载到目标板上，并且没有对核心源码及移植部分做修改？务必首先确保先把 GitHub 上的最新源码在目标板上成功运行成功起来。

**Comment by lmyun** [comment]
反应很快，谢谢！问题解决了，是我自己没enable port。
