### ISSUE TITLE
modbus tcp wifi

### ISSUE THREAD

**Issue by heroseller17** [armink/FreeModbus_Slave-Master-RTT-STM32#21]
Hello
is there any way to use wifi modbus tcp slave on stm or nxp lpc?

**Comment by armink** [comment]
I have not use modbus tcp. You can test this demo( https://github.com/xukai871105/uip_freemodbus_tcp ) for freemodbus tcp.

**Comment by heroseller17** [comment]
so what kind of modbus does this library support?

**Comment by armink** [comment]
https://github.com/armink/FreeModbus_Slave-Master-RTT-STM32 this library?

**Comment by heroseller17** [comment]
yes it dosent support modbus slave master tcp/ip for cmsis(stm32 or lpc17xx)?

**Comment by armink** [comment]
yes, just support modbus rtu slave and master.
