### ISSUE TITLE
xMBRTUReceiveFSM assert_param(eSndState == STATE_TX_IDLE)断言失败

### ISSUE THREAD

**Issue by kuangrenjing** [armink/FreeModbus_Slave-Master-RTT-STM32#34]
使用串口工具调试modbus_slaver，STM32死在了xMBRTUReceiveFSM函数assert_param(eSndState == STATE_TX_IDLE)调用处，mbrtu.c 312 313行交换顺序后此问题不再出现。

**Comment by armink** [comment]
see #35
