### ISSUE TITLE
关于sem value初始化为1的问题

### ISSUE THREAD

**Issue by hongguangli** [armink/FreeModbus_Slave-Master-RTT-STM32#41]
你好，请问一下，下面sem_init这里的value设置为了0x01,那么take时就算没有接收到任何数据，也能直接return，也就导致了timeout设置失效。为什么要设置为1，而不是设置为0呢？thx.
void vMBMasterOsResInit( void )
{
    rt_sem_init(&xMasterRunRes, "master res", 0x01 , RT_IPC_FLAG_PRIO);
}

**Comment by armink** [comment]
take sem 在这里的用处好像更像是资源锁
