### ISSUE TITLE
port.c 中 EnterCriticalSection（）函数填充错误

### ISSUE THREAD

**Issue by guoweilkd** [armink/FreeModbus_Slave-Master-RTT-STM32#44]
port.c中的 `EnterCriticalSection（）`函数和 `ExitCriticalSection（）`函数为何填充的是**关/开中断**的语句？在接收函数和发送函数中都调用了这两个函数，这对中断的响应实时性有太大的影响了？是否应该更改为**关调度，开调度**。不过感觉关调度和开调度也不是太好

**Comment by armink** [comment]
你可以试试哈，感觉是没问题的，期待你的测试结果哈

**Comment by guoweilkd** [comment]
试了一下，关调度目前没有发现问题，而且之前关中断造成的采样数据丢失也得到了保证。

**Comment by armink** [comment]
OK ~~欢迎提交 pr 哈
