### ISSUE TITLE
关于Master使用方式疑问

### ISSUE THREAD

**Issue by MayeManfred** [armink/FreeModbus_Slave-Master-RTT-STM32#7]
首先非常感谢您能开源代码供大家学习。本人菜鸟一枚，有一问题想问，运行master程序的话是不是必须要单独开一个任务（线程）运行eMBMasterPoll，然后在其他任务里执行具体的控制命令？这样做是不是太过麻烦了，我公司有一个大牛自己写的modbus协议，用的ucos2，运行主机时不需要单独建立任务，直接使用控制函数就好，好像是用信号量做的，你的这个是不是也可以这样做。

**Comment by haitao52198** [comment]
@armink T1.5是什么时间单位呢？  我没有细看这个协议，看了下libmodbus里的实现，移植起来貌似更容易，所以我就移植了下libmodbus，里面有个地方用了windows的串口超时的机制，还没有细细研究，就是想起你这里用了定时器，我是不想用硬件定时器，就想咨询下FIFO的超时是否能够实现？

**Comment by haitao52198** [comment]
@armink  知道了，T1.5是750us， T3.5是1.75ms

**Comment by armink** [comment]
@haitao52198 最新版本的定时器就是用的RT-Thread系统自带的软件定时器，你可以看下
https://github.com/armink/FreeModbus_Slave-Master-RTT-STM32/blob/master/FreeModbus/port/rtt/porttimer.c#L37

**Comment by haitao52198** [comment]
@armink 确定是软件定时器么？我记得软件定时器的精度是系统的tick呢，这里是不是还是硬件定时器呢，看来硬件定时器是避免不了了的样子。

**Comment by armink** [comment]
@haitao52198 看来你还不了解RT-Thread，建议先看下RT-Thread定时器功能吧。软件定时器代码没问题，都是测试通过的。

**Comment by haitao52198** [comment]
@armink 我不想牵扯到了解多深的问题，我只是委婉的说，RTT的软件定时器精度最小是tick，文档里也有说明，看看代码的实现，就是一个优先级最高的线程在处理软件定时器队列，所以精度有限，但是如果是硬件定时器，那就没有问题了，要么就是你的叙述不严谨。通过测试的东西多了，但是不代表不存在隐患或者bug！

**Comment by armink** [comment]
@haitao52198 之前你一直在疑惑是不是软件定时器，我明确的告诉了是软件定时器而已，这么简单的回答，不理解你说的问题高深在什么地方？另外，RTT Tick的精度是可配置的，如果你想使用硬件定时器使用之前版本就好，不用这较真

**Comment by haitao52198** [comment]
@armink 
/* Using Software Timer */
/* #define RT_USING_TIMER_SOFT */
#define RT_TIMER_THREAD_PRIO		4
#define RT_TIMER_THREAD_STACK_SIZE	512
#define RT_TIMER_TICK_PER_SECOND	1000
你的工程里找了半天你的rt_config.h，好不容易找到，一点RTT的风格都木有了。你连使用软件定时器的宏都没有打开，不知道你的软件定时器是怎么用的，我平时不是一个较真的人，今天就跟在这你较真了。

**Comment by armink** [comment]
@haitao52198  开启RT_USING_TIMER_SOFT宏叫做**软定时**，RTT的软件定时器自带两种定时模式，即**软定时**与**硬定时**，我用的是RTT软件定时器的**硬定时**模式，难道这不是软件定时器？

这是RTT手册上的标准定义：硬件定时器是芯片本身提供的定时功能（例如STM32的Timer1、2），而软件定时器是由操作系统提供的一类系统接口（函数）。

搞技术的最怕较真，较真会让你带着情绪看问题。

**Comment by yyjpeter** [comment]
好
